name: GitHub-CICD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  scan:
    name: Gitleaks Scan
    runs-on: SelfHosted-GitHub-Runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v6
