name: GitHub-CICD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  scan:
    name: Gitleaks Scan
    runs-on: SelfHosted-GitHub-Runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan Current Directory
        run: |
          pwd
          ls -la
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
